### ISSUE TITLE
feat: add more well-known fields by default

### ISSUE THREAD

**Issue by JounQin** [privatenumber/clean-pkg-json#1]
Reference: https://angular.io/guide/angular-package-format#legacy-resolution-keys

Related fields: `fesm2020` / `fesm2015` / `esm2020` / `es2020`

I'm glad to raise a PR for it.

**Comment by privatenumber** [comment]
Im open to supporting 3rd party properties (eg. `unpkg`, `ember`, etc) via `preset` flag:

```
clean-pkg-json --preset angular -p unpkg
```

What do you think?

**Comment by JounQin** [comment]
In https://github.com/ai/size-limit, it will read all presets automatically. So I think a plugin system would be much easier to use and keep the core slim.

**Comment by privatenumber** [comment]
Not sure if I understand. What's the relevance of [ai/size-limit](https://github.com/ai/size-limit)?

**Comment by JounQin** [comment]
> Not sure if I understand. What's the relevance of [ai/size-limit](https://github.com/ai/size-limit)?

Sorry for the confusion.

I mean, it can read package whether `clean-pkg-json-preset-angular` exist, then preset `angular` could be used automatically.

**Comment by privatenumber** [comment]
Not sure if it makes sense to publish & install a package just for 4 strings: `["fesm2020", "fesm2015", "esm2020", "es2020"]`

In the case of [unpkg](https://unpkg.com/#:~:text=If%20you%20omit%20the%20file%20path%20(i.e.%20use%20a%20%E2%80%9Cbare%E2%80%9D%20URL)%2C%20unpkg%20will%20serve%20the%20file%20specified%20by%20the%20unpkg%20field%20in%20package.json%2C%20or%20fall%20back%20to%20main.), it would be a single string: `["unpkg"]`

**Comment by JounQin** [comment]
@privatenumber 

So if there're built-in presets, I have no idea why they should be presets rather than defaults?

**Comment by privatenumber** [comment]
Good point. I'm open to adding it without presets.

I can't think of real examples but I was thinking if multiple tools use the same package.json property, where one uses it in development and the other in application, the first usage might want that property removed but the second wont. 

Aside from that, a benefit would be semantics. It's much easier to understand what's happening:
`clean-pkg-json --preset angular`

**Comment by JounQin** [comment]
> Aside from that, a benefit would be semantics. It's much easier to understand what's happening:
clean-pkg-json --preset angular

I still don't understand what's the benefits. If the presets presented, it means the user want it. For example, why would a user add `es2020` but don't want it on production?

**Comment by privatenumber** [comment]
My point with the sentence you quoted is that it helps with writing more readable code. For a beginner joining a codebase, reading `--preset angular` improves understanding.

My earlier point is that we shouldn't assume. We can also ask "why _would_ the user want the `es2020` property preserved for production?" and the answer is "we don't know". There could be many bad reasons for it; a lot of people copy-paste code without understanding it.

Anyway, like I said, I'm open to adding it without presets.
